# Site settings
title: lalala~
email: zhouxj327@sina.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://archer811.com" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  archer811

# Build settings
markdown: kramdown
paginate: 10  
paginate_path: "page:num"
